apiVersion: apps/v1
kind: Deployment
metadata:
  name: har
spec:
  replicas: 1
  selector:
    matchLabels:
      app: har
  template:
    metadata:
      labels:
        app: har
    spec:
      containers:
      - image: okteto.dev/har:latest
        name: har
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.crazygames.com"
        - name: Vless_UUID
          value: "4c45c9c2-2edd-4161-9db7-a15d6820fda4"
        - name: Vless_Path
          value: "/dfgbkr2"
        - name: Vmess_UUID
          value: "4c45c9c2-2edd-4161-9db7-a15d6820fda4"
        - name: Vmess_Path
          value: "/GBJKOP2r"
        - name: Share_Path
          value: "/Share532"
