apiVersion: apps/v1
kind: Deployment
metadata:
  name: war
spec:
  replicas: 1
  selector:
    matchLabels:
      app: war
  template:
    metadata:
      labels:
        app: war
    spec:
      containers:
      - image: okteto.dev/war:latest
        name: war
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "4dc4d0ae-55ee-4039-99ea-1efe73868b06"
        - name: Vless_Path
          value: "/lugqwerd43"
        - name: Vmess_UUID
          value: "4dc4d0ae-55ee-4039-99ea-1efe73868b06"
        - name: Vmess_Path
          value: "/fcsdter56"
        - name: Share_Path
          value: "/Share602"
