apiVersion: apps/v1
kind: Deployment
metadata:
  name: poile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poile
  template:
    metadata:
      labels:
        app: poile
    spec:
      containers:
      - image: okteto.dev/poile:latest
        name: poile
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.moviecrumbs.net "
        - name: Vless_UUID
          value: "0288abe9-f391-412c-a6cc-060b58971c0e"
        - name: Vless_Path
          value: "/DANdsv"
        - name: Vmess_UUID
          value: "0288abe9-f391-412c-a6cc-060b58971c0e"
        - name: Vmess_Path
          value: "/argasd"
        - name: Share_Path
          value: "/Share901"
