apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcot
  template:
    metadata:
      labels:
        app: swet
    spec:
      containers:
      - image: okteto.dev/dcot:latest
        name: dcot
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.azmovies.net "
        - name: Vless_UUID
          value: "8b66a22c-356e-43b6-a36d-6a1263505547"
        - name: Vless_Path
          value: "/JK09sdvf"
        - name: Vmess_UUID
          value: "8b66a22c-356e-43b6-a36d-6a1263505547"
        - name: Vmess_Path
          value: "/GBMedf6"
        - name: Share_Path
          value: "/Share345"
