apiVersion: apps/v1
kind: Deployment
metadata:
  name: faret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faret
  template:
    metadata:
      labels:
        app: faret
    spec:
      containers:
      - image: okteto.dev/faret:latest
        name: faret
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw "
        - name: Vless_UUID
          value: "0682bff8-ba4c-4386-a45d-4e858869abf4"
        - name: Vless_Path
          value: "/frbFVFG5"
        - name: Vmess_UUID
          value: "0682bff8-ba4c-4386-a45d-4e858869abf4"
        - name: Vmess_Path
          value: "/CVBHNGds"
        - name: Share_Path
          value: "/Share432"
