apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcot
  template:
    metadata:
      labels:
        app: dcot
    spec:
      containers:
      - image: okteto.dev/dcot:latest
        name: dcot
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.azmovies.net "
        - name: Vless_UUID
          value: "e8d0aff9-8e88-453b-84e7-2fdf5f289384"
        - name: Vless_Path
          value: "/JK09sdvf"
        - name: Vmess_UUID
          value: "e8d0aff9-8e88-453b-84e7-2fdf5f289384"
        - name: Vmess_Path
          value: "/GBMedf6"
        - name: Share_Path
          value: "/Share345"
