apiVersion: apps/v1
kind: Deployment
metadata:
  name: trecd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trecd
  template:
    metadata:
      labels:
        app: trecd
    spec:
      containers:
      - image: okteto.dev/trecd:latest
        name: trecd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "beauty-upgrade.tw "
        - name: Vless_UUID
          value: "fde9f6de-b995-40bb-acea-6b7294b06b8f"
        - name: Vless_Path
          value: "/stwkmfbDAF"
        - name: Vmess_UUID
          value: "fde9f6de-b995-40bb-acea-6b7294b06b8f"
        - name: Vmess_Path
          value: "/FAZBOP2"
        - name: Share_Path
          value: "/Share312"
