apiVersion: apps/v1
kind: Deployment
metadata:
  name: yer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yer
  template:
    metadata:
      labels:
        app: yer
    spec:
      containers:
      - image: okteto.dev/yer:latest
        name: yer
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.flexclip.com"
        - name: Vless_UUID
          value: "21d3a188-7c12-456e-9827-d8a0c28494ea"
        - name: Vless_Path
          value: "/YJKPLSA"
        - name: Vmess_UUID
          value: "21d3a188-7c12-456e-9827-d8a0c28494ea"
        - name: Vmess_Path
          value: "/dcbnmaw"
        - name: Share_Path
          value: "/Share601"
