apiVersion: apps/v1
kind: Deployment
metadata:
  name: watiy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watiy
  template:
    metadata:
      labels:
        app: watiy
    spec:
      containers:
      - image: okteto.dev/watiy:latest
        name: watiy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "moviemora.com "
        - name: Vless_UUID
          value: "d54452df-7d31-448c-a17e-cb3876e84f2f"
        - name: Vless_Path
          value: "/FDhbvp"
        - name: Vmess_UUID
          value: "d54452df-7d31-448c-a17e-cb3876e84f2f"
        - name: Vmess_Path
          value: "/yhjmkps"
        - name: Share_Path
          value: "/Share560"
