apiVersion: apps/v1
kind: Deployment
metadata:
  name: swet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swet
  template:
    metadata:
      labels:
        app: swet
    spec:
      containers:
      - image: okteto.dev/swet:latest
        name: swet
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.anime-planet.com "
        - name: Vless_UUID
          value: "90a39920-e84c-457b-bf4d-2fd7adc07fc2"
        - name: Vless_Path
          value: "/QFBMjok"
        - name: Vmess_UUID
          value: "90a39920-e84c-457b-bf4d-2fd7adc07fc2"
        - name: Vmess_Path
          value: "/FGBNM"
        - name: Share_Path
          value: "/Share123"
