apiVersion: apps/v1
kind: Deployment
metadata:
  name: kec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kec
  template:
    metadata:
      labels:
        app: kec
    spec:
      containers:
      - image: okteto.dev/kec:latest
        name: kec
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "clipchamp.com "
        - name: Vless_UUID
          value: "5163328f-5aba-4edb-ab79-cbf28daa6966"
        - name: Vless_Path
          value: "/pactes32"
        - name: Vmess_UUID
          value: "5163328f-5aba-4edb-ab79-cbf28daa6966"
        - name: Vmess_Path
          value: "/EGBKL2de"
        - name: Share_Path
          value: "/Share523"
